version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql

  api:
    container_name: api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PORT: 3000
      POSTGRES_DATABASE_URL: postgres://root:root@db:5432/library
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
