POST http://localhost:3000/editoras
Content-Type: application/json

{
  "name": "Editora 1",
  "document": "12345678901234"
}

###

POST http://localhost:3000/livros
Content-Type: application/json

{
  "title": "Livro 1",
  "author": "Autor 1",
  "isbn": "1234567890",
  "published_at": 2020,
  "publisher_id": "1b8c3c3c-9cda-4cb8-9ddf-620e742a03f8"
}

###

GET http://localhost:3000/livros/c93a17c1-2b24-4156-a08d-672e405df0fc
Content-Type: application/json

###

GET http://localhost:3000/editoras/f9da1754-9fb6-4bac-8147-6029c7a14757
Content-Type: application/json

###

PUT http://localhost:3000/editoras/f9da1754-9fb6-4bac-8147-6029c7a14757
Content-Type: application/json

{
  "name": "Editora 2",
  "document": "12345678901234"
}

###

PUT http://localhost:3000/livros/855fb7bb-40a1-4433-8db6-92a1dcf20680
Content-Type: application/json

{
  "title": "Livro 2",
  "author": "Autor 2",
  "isbn": "1234567892",
  "published_at": 2024,
  "publisher_id": "1b8c3c3c-9cda-4cb8-9ddf-620e742a03f8"
}

###

GET http://localhost:3000/livros
Content-Type: application/json

###

GET http://localhost:3000/editoras
Content-Type: application/json

###

DELETE http://localhost:3000/livros/855fb7bb-40a1-4433-8db6-92a1dcf20680
Content-Type: application/json

###

DELETE http://localhost:3000/editoras/f9da1754-9fb6-4bac-8147-6029c7a14757
Content-Type: application/json
