POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "joao",
  "password": "12345678901"
}

###

POST http://localhost:3000/users/sign-in
Content-Type: application/json

{
  "username": "joao",
  "password": "12345678901"
}

###

POST http://localhost:3000/persons
Content-Type: application/json

{
  "cpf": "12345678901",
  "name": "João",
  "birth": "2023-01-01",
  "email": "joao@email.com",
  "user_id": 1
}

###

GET http://localhost:3000/users/1
Content-Type: application/json

###

POST http://localhost:3000/address
Content-Type: application/json

{
  "street": "Rua de São Paulo, 123 - Vila Olímpia",
  "city": "São Paulo",
  "state": "SP",
  "zipcode": "01234567",
  "person_id": 1
}

###

GET http://localhost:3000/address/1?page=1&limit=10
Content-Type: application/json

###

POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvYW8iLCJpYXQiOjE3MTg2NzM3MDgsImV4cCI6MTcxODY3NzMwOH0.5AkU7fETcbdMdx5Kx4tcDnpifmr0bzoraJaJe7UwV_I

{
  "name": "Bolinha integração",
  "description": "Bolinha legal",
  "image_url": "https://via.placeholder.com/150",
  "price": 49.90,
  "categories": [
    {
      "id": 1,
      "name": "Brinquedo"
    }
  ]
}

###

POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Brinquedo"
}

###

GET http://localhost:3000/products
Content-Type: application/json

###

GET http://localhost:3000/products/a8b85172-04f0-437b-a544-d35186cc70b8
Content-Type: application/json

###

PUT http://localhost:3000/products/a8b85172-04f0-437b-a544-d35186cc70b8
Content-Type: application/json

{
  "name": "Bolinha 2",
  "description": "Bolinha legal",
  "image_url": "https://via.placeholder.com/150",
  "price": 49.90,
  "categories": [
    {
      "id": 1,
      "name": "Brinquedo"
    }
  ]
}

###

DELETE http://localhost:3000/products/3e3c23c2-99f5-42df-a0d1-32dac082b301
Content-Type: application/json

###
