POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "joao",
  "password": "12345678901"
}

###

POST http://localhost:3000/persons
Content-Type: application/json

{
  "cpf": "12345678901",
  "name": "João",
  "birth": "2023-01-01",
  "email": "joao@email.com",
  "user_id": 1
}

###

GET http://localhost:3000/users/1
Content-Type: application/json

###

POST http://localhost:3000/address
Content-Type: application/json

{
  "street": "Rua de São Paulo, 123 - Vila Olímpia",
  "city": "São Paulo",
  "state": "SP",
  "zipcode": "01234567",
  "person_id": 1
}

###

GET http://localhost:3000/address/1?page=1&limit=10
Content-Type: application/json

###
